### ISSUE TITLE
Some kind of bug makes dissapear twitter icon/link on reload

### ISSUE THREAD

**Issue by rodoviario** [DurableDrupal/durabledrupal.org#1]
I will, for the moment, duplicate the entity and set the first to hide (it will disappear anyway)

**Comment by victorkane** [comment]
Actually, in the browser console we see the following message:

> [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

So this is either a bug, or, what it says, incorrect HTML markup.

Perhaps the best solution for now: stop using buttons for the social network icons, just use a flat icon in text?

**Comment by rodoviario** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scaffold pages](https://trello.com/c/s6nsslVe/3-scaffold-pages)
